#!/bin/sh
# open browser with google and use text selection as search pattern

BROWSER=firefox
BASEURL="http://www.google.de/search?hl=de&q="
SEARCH=$(xclip -o | sed 's/ /%20/g')
$BROWSER $BASEURL$SEARCH
